config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admin/sessions"}
  devise_for :users, controllers: {sessions: "user/sessions"}
		resources :posts do
			resources :comments
		end
    root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title
	validates_length_of :title, :in=> 5..30, :message=>"Titulo invalido"
	validates_presence_of :body
	validates :body, length: { minimum: 10, message: "El texto del post es demasiado corto" }
	validates :body, length: { maximum: 500, message: "El texto del post es demasiado largo" }
	has_many :comments, dependent: :destroy
	validates_presence_of :title
	validates_presence_of :body
	belongs_to :users
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        flash[:success] = "Se guardo correctamente el post"
        format.html {redirect_to @post}
        format.json { render :show, status: :created, location: @post }
      else
        flash[:alert] = 'Ocurrio un problema al guardar el post'
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    </div>
</div>
</ul>
      
<ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
      </div>
</div>
    </ul>
      


 <section class="row">
<div class="small-4 colums">
    <div class="actions">
        <%= f.submit 'Aceptar',:class => 'button small' %>
    </div>
    </div>

</section>



<% end %>

app/views/posts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu" data-dropdown-menu>
      <li class="menu-text">Practica Rails</li>
      <li><%= link_to "home", controller: "/posts", action: "index" %></li>
      <li><% if user_signed_in? %>
             <%= link_to "nuevo post", controller: "/posts", action: "new" %>        
          <%end%>          
          </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
       <% if user_signed_in? %>
        <li> <strong><%= current_user.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
       
       <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
       <%end%>
        <% if !user_signed_in? && !admin_signed_in? %> 
       <li> <%= link_to "Sign up user", new_user_registration_path, :class => 'navbar-link' %> </li>
       <li> <%= link_to "Login user", new_user_session_path, :class => 'navbar-link' %> </li>
       <li> <%= link_to "Login admin", new_admin_session_path, :class => 'navbar-link' %> </li>
        <% end %>
        
        <% if !user_signed_in? && admin_signed_in? %>
        <li> <strong><%= current_admin.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %></li>
       
        <li> <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
          <td>  
              <% if post.body.length > 0 %>
            <a href="#" data-open="post-<%= post.id %>">Ver Posts </a>
            <div id="post-<%= post.id%>" class="reveal" data-reveal>
                <%= post.body %>
                <button class="close-button" data-close aria-label="cerrar" type="button">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
              <% end %>
          </td>
          <% if admin_signed_in?%>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
        <%end%>         
              <% if user_signed_in? %>
            <td><%= link_to 'Show', post %></td>
             <td><%= link_to 'Edit', edit_post_path(post) %>               
             </td>
                    
          <%end%>
          
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <% if user_signed_in? %>
             <%= link_to 'New Post', new_post_path %>
              <% else %>
            
           
          
          <%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
	
<div id="comments">
	<%= render :partial=> @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
<p><%=f.label :body, "New Comment"%><br/>
<%=f.text_area :body %>
</p>

	<p><%=f.submit "Add Comment" %></p>
<% end -%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>